# Create a Namespace to hold the Channel
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: mcm-mgmt-channel
  namespace: mcm-mgmt-channel
spec:  
    type: HelmRepo
    secretRef:
      name: helm-repo-secret
      namespace: mcm-cert-manager
    configRef:
      name: insecure-skip-verify
      namespace: mcm-cert-manager
    pathname: <<ICP CONSOLE URL>>/mgmt-repo/charts  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: insecure-skip-verify
  namespace: mcm-mgmt-channel
data:
  insecureSkipVerify: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-secret
  namespace: mcm-mgmt-channel
data:
  user: <<SOME BASE64 USER>>
  password: <<SOME BASE64 PASSWORDS>>
